version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@2.1.0
  eb: circleci/aws-elastic-beanstalk@1.0.0

  # different jobs are calles later in the workflows sections
workflows:
  build-and-test:
    jobs:
      build:
        branches:
          only:
            - main
            - /rc-.*/
        docker:
          # the base image can run most needed actions with orbs
          - image: "cimg/base:stable"
    steps:
      - node/install
      - aws-cli/setup
      - eb/setup
      - checkout
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - deploy:
          name: eb init www
          command: |
            cd udagram-api/www && eb init --region us-east-1 www-dev
      - deploy:
          name: Deploy to Backend Elastic Beanstalk
          command: |
            cd udagram-api/www && eb deploy Wwwdev-env
      - deploy:
          name: set env variable
          command: |
            cd udagram-api && npm run deploy
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End deploy
          command: |
            npm run frontend:deploy

